# Generated by Django 2.2.3 on 2019-08-24 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customer_favourite_savedmap_savedmapfield_savedmaptag_tag'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='api_customers',
        ),
    ]
