# Generated by Django 2.2.3 on 2019-08-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190824_1149'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='favourite',
            table='api_favourites',
        ),
        migrations.AlterModelTable(
            name='savedmap',
            table='api_saved_maps',
        ),
        migrations.AlterModelTable(
            name='savedmapfield',
            table='api_saved_map_fields',
        ),
        migrations.AlterModelTable(
            name='savedmaptag',
            table='api_saved_map_tags',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='api_tags',
        ),
    ]
